### ISSUE TITLE
Discussion: Tracker Class

### ISSUE THREAD

**Issue by harell** [data-science-competitions/Modeling-Earthquake-Damage#22]
ModelTracker is a class that stores artifacts and metadata about the modelling process.

There are two apt software pattern: strategy and template.

- [ ] Draw UML for each design
- [ ] See list of signature functions [here](https://www.mlflow.org/docs/latest/R-api.html)
   - You can replace the "mlflow_" prefix with "tracker_"
- [ ] Two plugin suggestions are: mlflow and mockflow.
